apiVersion: apps/v1
kind: Deployment
metadata:
  name: infratokenarchitecture
spec:
  selector:
    matchLabels:
      app: infratokenarchitecture
  template:
    metadata:
      labels:
        app: infratokenarchitecture
    spec:
      containers:
      - name: infratokenarchitecture
        image: ghcr.io/marciohideaki/infratokenarchitecture:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          value: 'Infratoken'
        
