version: '0.1.0'

services:
  infratokenarchitecture:
    image: infratoken-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
