apiVersion: apps/v1
kind: Deployment
metadata:
  name: infratoken-service
spec:
  selector:
    matchLabels:
      app: infratoken-service
  template:
    metadata:
      labels:
        app: infratoken-service
    spec:
      containers:
      - name: infratoken-service
        image: ghcr.io/marciohideaki/infratokenpoc:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          value: 'Infratoken'
          readinessProbe:
            httpGet:
            path: /healthcheck
            port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
        
